### ISSUE TITLE
Criação das entidades

### ISSUE THREAD

**Issue by SebastianIzydorio** [ifpe-cti/servicon-web#3]
Criação das entidades de acordo com o diagrama de classe.

**Comment by fabriciofx** [comment]
@SebastianIzydorio Quais entidades? Qual diagrama de classe? Onde está esse diagrama? Seja mais específico, e quando citar algum documento, este documento tem que estar antes no repositório, certo?

**Comment by lucasmendsc** [comment]
@SebastianIzydorio poste o diagrama que fizemos,vamos verificar se já está bom para programarmos à partir dele.

**Comment by fabriciofx** [comment]
@lucasmendsc, @SebastianIzydorio, @MarcelaCCM vocês estão fazendo o fluxo de trabalho errado. Vocês **primeiro** abrem a issue, para **depois** realizar a atividade. Quem garante que o que vocês vão fazer está certo ou que deveria ser feito? Quem garante que essa atividade na verdade deveria ser quebrada em outra menores? Não houve a discussão, porque vocês não abriram a issue **antes**.

**Comment by lucasmendsc** [comment]
@fabriciofx sim,entendemos isso,por isso nós só esboçamos algo bem simples antes para ter algo em que nós possamos discutir em cima,mas essa issue foi aberta com a ideia de corrigirmos o fluxo.

**Comment by fabriciofx** [comment]
@lucasmendsc Desculpa, mas parece que ainda não entenderam. A issue você abre **antes** dizendo o que vai ser feito e por que será feito. **Depois** é que se faz alguma coisa. Da forma que vocês estão fazendo, corre o risco de ter trabalhado à toa. E se o orientador ou arquiteto diz: "isso não é pra ser feito" ou "isso não é prioridade". Como fica? Entendeu?

**Comment by lucasmendsc** [comment]
@fabriciofx entendido... Então,abrimos outra issue ou podemos começar a discussão sobre o assunto nessa mesma?

**Comment by fabriciofx** [comment]
@lucasmendsc Vai nessa mesma. O que vocês fizeram e porque fizeram?

**Comment by SebastianIzydorio** [comment]
Entendido,  irei abrir outra issue para discutir o assunto do diagrama. Quando terminarmos a mesma, voltaremos ao assunto da entidade. De acordo?

**Comment by fabriciofx** [comment]
@SebastianIzydorio Outro ponto: "entidades" é muito genérico. Tem que ser mais específico: Cadastro de Clientes, Cadastro de Profissional,  **uma funcionalidade por issue** (cuidado para não confundir uma classe por issue.
